repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.mlir$'
      - id: end-of-file-fixer
        exclude: '\.mlir$'
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=500']

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.6
    hooks:
      - id: clang-format
        types_or: [c, c++]
        exclude: '^(build/|wasmtime-executor/|local-executor/src/|mcu-wasm-executor/src/|benchmark/polybench/src/)'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
        args: ['--fix']
      - id: ruff-format

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ['--exclude=SC1091,SC2086,SC2016,SC2124,SC2166,SC2181']

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        additional_dependencies: ['cmakelang']

  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        entry: cargo fmt --manifest-path wasmtime-executor/Cargo.toml
        language: system
        types: [rust]
        pass_filenames: false
